import Navbar from '@/components/navbar/NavbarComponent'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-800 h-screen  flex flex-col w-screen`}>
          <Navbar />
          {children}
          
        
      </body>
    </html>
  )
}
