import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-screen flex flex-col'>
          <div className='h-20 bg-slate-800'></div>
          <div className='flex-grow'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
